// Code generated by protoc-gen-myjson-go. DO NOT EDIT IT!!!
// source: login.proto

/*
It has these top-level messages:
	S2C_Close
	C2S_Register
	S2C_Register
	C2S_Login
	S2C_Login
*/

package msg

import "fmt"
import "sync"
import protocol "github.com/trist725/mgsu/network/protocol/json"

var _ = fmt.Sprintf
var _ *sync.Pool
var _ = protocol.PH

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// message [S2C_Close] begin

/// 连接关闭 @msg
type S2C_Close struct {
	/// 关闭代码
	Err int32
}

func New_S2C_Close() *S2C_Close {
	m := &S2C_Close{}
	return m
}

func (m S2C_Close) String() string {
	ba, _ := json.Marshal(m)
	return fmt.Sprintf("{\"S2C_Close\":%s}", string(ba))
}

func (m *S2C_Close) Reset() {
	m.Err = 0

}

func (m S2C_Close) Clone() *S2C_Close {
	n, ok := g_S2C_Close_Pool.Get().(*S2C_Close)
	if !ok || n == nil {
		n = &S2C_Close{}
	}

	n.Err = m.Err

	return n
}

func Clone_S2C_Close_Slice(dst []*S2C_Close, src []*S2C_Close) []*S2C_Close {
	for _, i := range dst {
		Put_S2C_Close(i)
	}
	dst = []*S2C_Close{}

	for _, i := range src {
		dst = append(dst, i.Clone())
	}

	return dst
}

func (m *S2C_Close) Unmarshal(dAtA []byte) error {
	return json.Unmarshal(dAtA, m)
}

func (m S2C_Close) Marshal() (dAtA []byte, err error) {
	return json.Marshal(m)
}

func (S2C_Close) Json() {
}

func (S2C_Close) MessageID() protocol.MessageID {
	return "S2C_Close"
}

func S2C_Close_MessageID() protocol.MessageID {
	return "S2C_Close"
}

var g_S2C_Close_Pool = sync.Pool{}

func Get_S2C_Close() *S2C_Close {
	m, ok := g_S2C_Close_Pool.Get().(*S2C_Close)
	if !ok {
		m = New_S2C_Close()
	} else {
		if m == nil {
			m = New_S2C_Close()
		} else {
			m.Reset()
		}
	}
	return m
}

func Put_S2C_Close(i interface{}) {
	if m, ok := i.(*S2C_Close); ok && m != nil {
		g_S2C_Close_Pool.Put(i)
	}
}

func init() {
	Protocol.Register(
		&S2C_Close{},
		func() protocol.IMessage { return Get_S2C_Close() },
		func(msg protocol.IMessage) { Put_S2C_Close(msg) },
	)
}

// message [S2C_Close] end
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// message [C2S_Register] begin

/// 注册帐号请求 @msg
type C2S_Register struct {
	/// 帐号名
	AccountName string
	/// 密码
	Passwrod string
}

func New_C2S_Register() *C2S_Register {
	m := &C2S_Register{}
	return m
}

func (m C2S_Register) String() string {
	ba, _ := json.Marshal(m)
	return fmt.Sprintf("{\"C2S_Register\":%s}", string(ba))
}

func (m *C2S_Register) Reset() {
	m.AccountName = ""
	m.Passwrod = ""

}

func (m C2S_Register) Clone() *C2S_Register {
	n, ok := g_C2S_Register_Pool.Get().(*C2S_Register)
	if !ok || n == nil {
		n = &C2S_Register{}
	}

	n.AccountName = m.AccountName
	n.Passwrod = m.Passwrod

	return n
}

func Clone_C2S_Register_Slice(dst []*C2S_Register, src []*C2S_Register) []*C2S_Register {
	for _, i := range dst {
		Put_C2S_Register(i)
	}
	dst = []*C2S_Register{}

	for _, i := range src {
		dst = append(dst, i.Clone())
	}

	return dst
}

func (m *C2S_Register) Unmarshal(dAtA []byte) error {
	return json.Unmarshal(dAtA, m)
}

func (m C2S_Register) Marshal() (dAtA []byte, err error) {
	return json.Marshal(m)
}

func (C2S_Register) Json() {
}

func (C2S_Register) MessageID() protocol.MessageID {
	return "C2S_Register"
}

func C2S_Register_MessageID() protocol.MessageID {
	return "C2S_Register"
}

var g_C2S_Register_Pool = sync.Pool{}

func Get_C2S_Register() *C2S_Register {
	m, ok := g_C2S_Register_Pool.Get().(*C2S_Register)
	if !ok {
		m = New_C2S_Register()
	} else {
		if m == nil {
			m = New_C2S_Register()
		} else {
			m.Reset()
		}
	}
	return m
}

func Put_C2S_Register(i interface{}) {
	if m, ok := i.(*C2S_Register); ok && m != nil {
		g_C2S_Register_Pool.Put(i)
	}
}

func init() {
	Protocol.Register(
		&C2S_Register{},
		func() protocol.IMessage { return Get_C2S_Register() },
		func(msg protocol.IMessage) { Put_C2S_Register(msg) },
	)
}

// message [C2S_Register] end
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// message [S2C_Register] begin

/// 注册帐号结果 @msg
type S2C_Register struct {
	/// 错误码
	Err S2C_Register_E_Error
	/// 帐号名
	AccountName string
	/// 密码
	Password string
	/// 状态
	State S2C_Register_E_State
}

func New_S2C_Register() *S2C_Register {
	m := &S2C_Register{}
	return m
}

func (m S2C_Register) String() string {
	ba, _ := json.Marshal(m)
	return fmt.Sprintf("{\"S2C_Register\":%s}", string(ba))
}

func (m *S2C_Register) Reset() {
	m.Err = 0
	m.AccountName = ""
	m.Password = ""
	m.State = 0

}

func (m S2C_Register) Clone() *S2C_Register {
	n, ok := g_S2C_Register_Pool.Get().(*S2C_Register)
	if !ok || n == nil {
		n = &S2C_Register{}
	}

	n.Err = m.Err
	n.AccountName = m.AccountName
	n.Password = m.Password
	n.State = m.State

	return n
}

func Clone_S2C_Register_Slice(dst []*S2C_Register, src []*S2C_Register) []*S2C_Register {
	for _, i := range dst {
		Put_S2C_Register(i)
	}
	dst = []*S2C_Register{}

	for _, i := range src {
		dst = append(dst, i.Clone())
	}

	return dst
}

func (m *S2C_Register) Unmarshal(dAtA []byte) error {
	return json.Unmarshal(dAtA, m)
}

func (m S2C_Register) Marshal() (dAtA []byte, err error) {
	return json.Marshal(m)
}

func (S2C_Register) Json() {
}

func (S2C_Register) MessageID() protocol.MessageID {
	return "S2C_Register"
}

func S2C_Register_MessageID() protocol.MessageID {
	return "S2C_Register"
}

var g_S2C_Register_Pool = sync.Pool{}

func Get_S2C_Register() *S2C_Register {
	m, ok := g_S2C_Register_Pool.Get().(*S2C_Register)
	if !ok {
		m = New_S2C_Register()
	} else {
		if m == nil {
			m = New_S2C_Register()
		} else {
			m.Reset()
		}
	}
	return m
}

func Put_S2C_Register(i interface{}) {
	if m, ok := i.(*S2C_Register); ok && m != nil {
		g_S2C_Register_Pool.Put(i)
	}
}

func init() {
	Protocol.Register(
		&S2C_Register{},
		func() protocol.IMessage { return Get_S2C_Register() },
		func(msg protocol.IMessage) { Put_S2C_Register(msg) },
	)
}

// message [S2C_Register] end
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// message [C2S_Login] begin

/// 登录请求 @msg
type C2S_Login struct {
	/// 帐号名
	Account string
	/// 密码
	Password string
}

func New_C2S_Login() *C2S_Login {
	m := &C2S_Login{}
	return m
}

func (m C2S_Login) String() string {
	ba, _ := json.Marshal(m)
	return fmt.Sprintf("{\"C2S_Login\":%s}", string(ba))
}

func (m *C2S_Login) Reset() {
	m.Account = ""
	m.Password = ""

}

func (m C2S_Login) Clone() *C2S_Login {
	n, ok := g_C2S_Login_Pool.Get().(*C2S_Login)
	if !ok || n == nil {
		n = &C2S_Login{}
	}

	n.Account = m.Account
	n.Password = m.Password

	return n
}

func Clone_C2S_Login_Slice(dst []*C2S_Login, src []*C2S_Login) []*C2S_Login {
	for _, i := range dst {
		Put_C2S_Login(i)
	}
	dst = []*C2S_Login{}

	for _, i := range src {
		dst = append(dst, i.Clone())
	}

	return dst
}

func (m *C2S_Login) Unmarshal(dAtA []byte) error {
	return json.Unmarshal(dAtA, m)
}

func (m C2S_Login) Marshal() (dAtA []byte, err error) {
	return json.Marshal(m)
}

func (C2S_Login) Json() {
}

func (C2S_Login) MessageID() protocol.MessageID {
	return "C2S_Login"
}

func C2S_Login_MessageID() protocol.MessageID {
	return "C2S_Login"
}

var g_C2S_Login_Pool = sync.Pool{}

func Get_C2S_Login() *C2S_Login {
	m, ok := g_C2S_Login_Pool.Get().(*C2S_Login)
	if !ok {
		m = New_C2S_Login()
	} else {
		if m == nil {
			m = New_C2S_Login()
		} else {
			m.Reset()
		}
	}
	return m
}

func Put_C2S_Login(i interface{}) {
	if m, ok := i.(*C2S_Login); ok && m != nil {
		g_C2S_Login_Pool.Put(i)
	}
}

func init() {
	Protocol.Register(
		&C2S_Login{},
		func() protocol.IMessage { return Get_C2S_Login() },
		func(msg protocol.IMessage) { Put_C2S_Login(msg) },
	)
}

// message [C2S_Login] end
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// message [S2C_Login] begin

/// 登录回复 @msg
type S2C_Login struct {
	/// 错误码
	Err S2C_Login_E_Error
	/// 密钥
	Key string
	/// 服务器列表
	Server []*S2C_Login_ServerInfo
	/// 上次登录服务器ID
	LastLoginServerID int32
}

func New_S2C_Login() *S2C_Login {
	m := &S2C_Login{
		Server: []*S2C_Login_ServerInfo{},
	}
	return m
}

func (m S2C_Login) String() string {
	ba, _ := json.Marshal(m)
	return fmt.Sprintf("{\"S2C_Login\":%s}", string(ba))
}

func (m *S2C_Login) Reset() {
	m.Err = 0
	m.Key = ""

	for _, i := range m.Server {
		Put_S2C_Login_ServerInfo(i)
	}
	m.Server = []*S2C_Login_ServerInfo{}
	m.LastLoginServerID = 0

}

func (m S2C_Login) Clone() *S2C_Login {
	n, ok := g_S2C_Login_Pool.Get().(*S2C_Login)
	if !ok || n == nil {
		n = &S2C_Login{}
	}

	n.Err = m.Err
	n.Key = m.Key

	if len(m.Server) > 0 {
		for _, i := range m.Server {
			if i != nil {
				n.Server = append(n.Server, i.Clone())
			} else {
				n.Server = append(n.Server, nil)
			}
		}
	} else {
		n.Server = []*S2C_Login_ServerInfo{}
	}

	n.LastLoginServerID = m.LastLoginServerID

	return n
}

func Clone_S2C_Login_Slice(dst []*S2C_Login, src []*S2C_Login) []*S2C_Login {
	for _, i := range dst {
		Put_S2C_Login(i)
	}
	dst = []*S2C_Login{}

	for _, i := range src {
		dst = append(dst, i.Clone())
	}

	return dst
}

func (m *S2C_Login) Unmarshal(dAtA []byte) error {
	return json.Unmarshal(dAtA, m)
}

func (m S2C_Login) Marshal() (dAtA []byte, err error) {
	return json.Marshal(m)
}

func (S2C_Login) Json() {
}

func (S2C_Login) MessageID() protocol.MessageID {
	return "S2C_Login"
}

func S2C_Login_MessageID() protocol.MessageID {
	return "S2C_Login"
}

var g_S2C_Login_Pool = sync.Pool{}

func Get_S2C_Login() *S2C_Login {
	m, ok := g_S2C_Login_Pool.Get().(*S2C_Login)
	if !ok {
		m = New_S2C_Login()
	} else {
		if m == nil {
			m = New_S2C_Login()
		} else {
			m.Reset()
		}
	}
	return m
}

func Put_S2C_Login(i interface{}) {
	if m, ok := i.(*S2C_Login); ok && m != nil {
		g_S2C_Login_Pool.Put(i)
	}
}

func init() {
	Protocol.Register(
		&S2C_Login{},
		func() protocol.IMessage { return Get_S2C_Login() },
		func(msg protocol.IMessage) { Put_S2C_Login(msg) },
	)
}

// message [S2C_Login] end
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// message [S2C_Login_ServerInfo] begin

/// 服务器信息
type S2C_Login_ServerInfo struct {
	/// 服务器ID
	ID int32
	/// 服务器地址 = ip+端口+path, 例如: ws://127.0.0.1:8080/region1
	Addr string
	/// 服务器名
	Name string
}

func New_S2C_Login_ServerInfo() *S2C_Login_ServerInfo {
	m := &S2C_Login_ServerInfo{}
	return m
}

func (m S2C_Login_ServerInfo) String() string {
	ba, _ := json.Marshal(m)
	return fmt.Sprintf("{\"S2C_Login_ServerInfo\":%s}", string(ba))
}

func (m *S2C_Login_ServerInfo) Reset() {
	m.ID = 0
	m.Addr = ""
	m.Name = ""

}

func (m S2C_Login_ServerInfo) Clone() *S2C_Login_ServerInfo {
	n, ok := g_S2C_Login_ServerInfo_Pool.Get().(*S2C_Login_ServerInfo)
	if !ok || n == nil {
		n = &S2C_Login_ServerInfo{}
	}

	n.ID = m.ID
	n.Addr = m.Addr
	n.Name = m.Name

	return n
}

func Clone_S2C_Login_ServerInfo_Slice(dst []*S2C_Login_ServerInfo, src []*S2C_Login_ServerInfo) []*S2C_Login_ServerInfo {
	for _, i := range dst {
		Put_S2C_Login_ServerInfo(i)
	}
	dst = []*S2C_Login_ServerInfo{}

	for _, i := range src {
		dst = append(dst, i.Clone())
	}

	return dst
}

func (m *S2C_Login_ServerInfo) Unmarshal(dAtA []byte) error {
	return json.Unmarshal(dAtA, m)
}

func (m S2C_Login_ServerInfo) Marshal() (dAtA []byte, err error) {
	return json.Marshal(m)
}

var g_S2C_Login_ServerInfo_Pool = sync.Pool{}

func Get_S2C_Login_ServerInfo() *S2C_Login_ServerInfo {
	m, ok := g_S2C_Login_ServerInfo_Pool.Get().(*S2C_Login_ServerInfo)
	if !ok {
		m = New_S2C_Login_ServerInfo()
	} else {
		if m == nil {
			m = New_S2C_Login_ServerInfo()
		} else {
			m.Reset()
		}
	}
	return m
}

func Put_S2C_Login_ServerInfo(i interface{}) {
	if m, ok := i.(*S2C_Login_ServerInfo); ok && m != nil {
		g_S2C_Login_ServerInfo_Pool.Put(i)
	}
}

// message [S2C_Login_ServerInfo] end
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
