// Code generated by protoc-gen-myjson-go. DO NOT EDIT IT!!!
// source: version.proto

/*
It has these top-level messages:
	VersionInfo
*/

package msg

import "fmt"
import "sync"
import protocol "github.com/trist725/mgsu/network/protocol/json"

var _ = fmt.Sprintf
var _ *sync.Pool
var _ = protocol.PH

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// message [VersionInfo] begin

/// 版本信息
type VersionInfo struct {
	/// 测试协议5字段1
	Content string
	/// 测试协议5字段2
	D float64
	/// 测试协议5字段3
	F float32
	/// 测试协议5字段4
	I32 int32
	/// 测试协议5字段5
	I64 int64
	/// 测试协议5字段6
	Ui32 uint32
	/// 测试协议5字段7
	Ui64 uint64
	/// 测试协议5字段8
	B bool
	/// 测试协议5字段9
	Bytes []byte
}

func New_VersionInfo() *VersionInfo {
	m := &VersionInfo{
		Bytes: []byte{},
	}
	return m
}

func (m VersionInfo) String() string {
	ba, _ := json.Marshal(m)
	return fmt.Sprintf("{\"VersionInfo\":%s}", string(ba))
}

func (m *VersionInfo) Reset() {
	m.Content = ""
	m.D = 0.0
	m.F = 0.0
	m.I32 = 0
	m.I64 = 0
	m.Ui32 = 0
	m.Ui64 = 0
	m.B = false
	m.Bytes = []byte{}

}

func (m VersionInfo) Clone() *VersionInfo {
	n, ok := g_VersionInfo_Pool.Get().(*VersionInfo)
	if !ok || n == nil {
		n = &VersionInfo{}
	}

	n.Content = m.Content
	n.D = m.D
	n.F = m.F
	n.I32 = m.I32
	n.I64 = m.I64
	n.Ui32 = m.Ui32
	n.Ui64 = m.Ui64
	n.B = m.B

	if len(m.Bytes) > 0 {
		n.Bytes = make([]byte, len(m.Bytes))
		copy(n.Bytes, m.Bytes)
	} else {
		n.Bytes = []byte{}
	}

	return n
}

func Clone_VersionInfo_Slice(dst []*VersionInfo, src []*VersionInfo) []*VersionInfo {
	for _, i := range dst {
		Put_VersionInfo(i)
	}
	dst = []*VersionInfo{}

	for _, i := range src {
		dst = append(dst, i.Clone())
	}

	return dst
}

func (m *VersionInfo) Unmarshal(dAtA []byte) error {
	return json.Unmarshal(dAtA, m)
}

func (m VersionInfo) Marshal() (dAtA []byte, err error) {
	return json.Marshal(m)
}

var g_VersionInfo_Pool = sync.Pool{}

func Get_VersionInfo() *VersionInfo {
	m, ok := g_VersionInfo_Pool.Get().(*VersionInfo)
	if !ok {
		m = New_VersionInfo()
	} else {
		if m == nil {
			m = New_VersionInfo()
		} else {
			m.Reset()
		}
	}
	return m
}

func Put_VersionInfo(i interface{}) {
	if m, ok := i.(*VersionInfo); ok && m != nil {
		g_VersionInfo_Pool.Put(i)
	}
}

// message [VersionInfo] end
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
