// Code generated by protoc-gen-pbex-go. DO NOT EDIT IT!!!
// source: enums.proto

package msg

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// enum [Version] begin

/*
/ 协议版本枚举
*/

var Version_Slice = []int32{
	0,
	1,
}

func Version_Len() int {
	return len(Version_Slice)
}

func Check_Version_I(value int32) bool {
	if _, ok := Version_name[value]; ok && value != 0 {
		return true
	}
	return false
}

func Check_Version(value Version) bool {
	return Check_Version_I(int32(value))
}

func Each_Version(f func(Version) bool) {
	for _, value := range Version_Slice {
		if !f(Version(value)) {
			break
		}
	}
}

func Each_Version_I(f func(int32) bool) {
	for _, value := range Version_Slice {
		if !f(value) {
			break
		}
	}
}

// enum [Version] end
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
